### ISSUE TITLE
art.zip和art_noise.zip文件损坏

### ISSUE THREAD

**Issue by 1700127** [ViTAE-Transformer/ViTAE-Transformer-Scene-Text-Detection#1]
大佬你好，你提供的训练数据art.zip和art_noise.zip文件好像损坏了，可以重新上传更新下吗，谢谢
<img width="619" alt="image" src="https://user-images.githubusercontent.com/43924063/182518972-fa5ca143-342c-409b-b7c5-cae219f8ca9d.png">

**Comment by ymy-k** [comment]
已重新上传更新，感谢关注～～
