### ISSUE TITLE
如何训练自己的模型？

### ISSUE THREAD

**Issue by zhaoguoqing12** [ViTAE-Transformer/ViTAE-Transformer-Scene-Text-Detection#2]
我训练自己的数据，也要下载这些数据集吗？
Some offline augmented ArT training datasets are used. lsvt-test is only used to train SSL(Semi-Supervised Learning) model in paper. Files named train_lossweight.json are the provided pseudo-label for SSL training. You can download correspoding datasets in config file from here and put them in [data/](https://github.com/ViTAE-Transformer/ViTAE-Transformer-Scene-Text-Detection/blob/main/data):

**Comment by ymy-k** [comment]
不一定需要这些，根据你自己数据的数据量以及域差异看情况决定。

**Comment by zhaoguoqing12** [comment]
> 特别需要这些，根据你自己的数据量决定以及领域不同的情况。

我明白了 谢谢。
但我在训练中遇到了一个异常，您知道是为什么吗？
![image](https://user-images.githubusercontent.com/47818312/183241515-9970777a-b205-4e22-a6d8-7499edb9c01b.png)

**Comment by ymy-k** [comment]
数据那一块的配置文件修改了什么?

**Comment by ymy-k** [comment]
是训练ViTAE的模型吗，数据那块的配置文件看一下

**Comment by zhaoguoqing12** [comment]
> 块的配置文件看
![image](https://user-images.githubusercontent.com/47818312/183245504-b1d2e7d9-482b-4114-a33d-1306f1c3ae10.png)
![image](https://user-images.githubusercontent.com/47818312/183245554-7d29f5da-c662-40a9-9f81-29a1f4d9f82c.png)

是的，这块我只改了数据集路径和图片size

**Comment by zhaoguoqing12** [comment]
![image](https://user-images.githubusercontent.com/47818312/183245712-d11a8853-15c8-499d-a0c0-4f1f70c32920.png)
我通过修改报错这块，目前异常好像没有发生了

**Comment by ymy-k** [comment]
标注里有iscrowd=True的或者是有空的数据吗？

**Comment by zhaoguoqing12** [comment]
是有的 iscrowd=1的数据，不能存在这样的数据吗？

**Comment by zhaoguoqing12** [comment]
如果有空的话 可以更新一下最新版本的mmdetect，这版本我发现了好多mmdetct导致的小问题。

**Comment by ymy-k** [comment]
> 是有的 iscrowd=1的数据，不能存在这样的数据吗？
您之前训练遇到的异常是因为这个原因，我在报错的位置也更新了下～因为我这边iscrowd没起啥作用所以默认都设为0，您的检测任务对这个是有啥特殊需要吗。btw，您训练的时候可以调节一下ViTAE的drop_path_rate看看哪种情况效果好，一般0.2，配置文件里用的比这个大(在ICDAR19 ArT数据集上混合训练的时候0.3效果比较好)

**Comment by ymy-k** [comment]
> 是有的 iscrowd=1的数据，不能存在这样的数据吗？

您之前训练遇到的异常是因为这个原因，我在报错的位置也更新了下～因为我这边iscrowd没起啥作用所以默认都设为0，您的检测任务对这个是有啥特殊需要吗。btw，您训练的时候可以调节一下ViTAE的drop_path_rate看看哪种情况效果好，一般0.2，配置文件里用的比这个大(在ICDAR19 ArT数据集上混合训练的时候0.3效果比较好)

**Comment by ymy-k** [comment]
> 如果有空的话 可以更新一下最新版本的mmdetect，这版本我发现了好多mmdetct导致的小问题。

好主意，感谢提醒，复现的时候没注意。这个版本的mmdetect您遇到哪些问题了方便说一下嘛

**Comment by zhaoguoqing12** [comment]
> > 是有的 iscrowd=1的数据，不能存在这样的数据吗？
> 
> 您之前训练遇到的异常是因为这个原因，我在报错的位置也更新了下～因为我这边iscrowd没起啥作用所以默认都设为0，您的检测任务对这个是有啥特殊需要吗。btw，您训练的时候可以调节一下ViTAE的drop_path_rate看看哪种情况效果好，一般0.2，配置文件里用的比这个大(在ICDAR19 ArT数据集上混合训练的时候0.3效果比较好)

好的 我会试一下的。

**Comment by zhaoguoqing12** [comment]
> > 如果有空的话 可以更新一下最新版本的mmdetect，这版本我发现了好多mmdetct导致的小问题。
> 
> 好主意，感谢提醒，复现的时候没注意。这个版本的mmdetect您遇到哪些问题了方便说一下嘛

目前出现错误有
1.使用单gpu训练训练中出现此异常
训练命令 CDA_VISIBLE_DEVICES=1 nohup python -u tools/train.py configs/i3cl_vitae_fpn/i3cl_vitae_fpn_ms_train.py --work-dir ./out_dir/v1 &
AssertionError: loss log variables are different across GPUs! 
rank 2 len(log_vars): 21 keys: interm_loss_cls,interm_loss_bbox,interm_loss_iou,loss_cls,loss_bbox,loss_iou,d0.loss_cls,d0.loss_bbox,d0.loss_iou,d1.loss_cls,d1.loss_bbox,d1.loss_iou,d2.loss_cls,d2.loss_bbox,d2.loss_iou,d3.loss_cls,d3.loss_bbox,d3.loss_iou,d4.loss_cls,d4.loss_bbox,d4.loss_iou
原因是数据中存在没有 bbox ground-truth 的图像会导致此问题，mmdetct之前没有兼容。
2.loss_mask：0.0084，损失：0.9420
2022-08-09 12:50:19,608 - mmdet - INFO - Epoch [1] [1812/1950] lr：1.000e-04，eta：17:07:52，时间：2.203， data_time: 0.733, memory: 17367, loss_rpn_cls: 0.2027, loss_rpn_bbox: 0.0440, loss_cls: 0.2284, acc: 91.6016, loss_bbox: 0.2649, loss_mask: 0.0194, loss: 0.7595
ERROR:torch.distributed.elastic.multiprocessing.api: ：-9）local_rank：1（pid：20277）二进制：/local_data/li/anaconda3/bin/python
错误：torch.distributed.elastic.agent.server.local_elastic_agent：[默认]工作组失败
信息：torch.distributed .elastic.agent.server.api：[默认] 工作组失败。还剩 3/3 次尝试；将重启工作组
INFO:torch.distributed.elastic.agent.server.api:[default] 停止工作组
INFO:torch.distributed.elastic.agent.server.api:[default] Rendezvous'ing 工作组
INFO:torch.distributed.elastic.agent.server.api:[default] 工作人员的集合完成。结果：
restart_count=1
master_addr=127.0.0.1
master_port=19997
group_rank=0
group_world_size=1
local_ranks=[0, 1]
role_ranks=[0, 1]
global_ranks=[0, 1]
role_world_sizes=[2, 2]
global_world_sizes=[ 2, 2]

INFO:torch.distributed.elastic.agent.server.api:[default] 启动工作组
INFO:torch.distributed.elastic.multiprocessing:将worker0回复文件设置为：/tmp/torchelastic_21195b1e/none__bsqzk__/attempt_1/0/error.json
INFO：torch.distributed.elastic.multiprocessing：将worker1回复文件设置为：/tmp/torchelastic_21195b1e/none__bsqzk__/attempt_1/1/error.json
3.使用多个GPU时，出现此异常
Timed out initializing process group in store based barrier on rank: 0, for key: store_based_barrier_key:1 (world_size=1, worker_count=4, timeout=0:30:00)

这些都在训练中报出的异常，是在迭代了上千次后出现的。

我的环境：
sys.platform: linux
Python: 3.7.6 (default, Jan  8 2020, 19:59:22) [GCC 7.3.0]
CUDA available: True
GPU 0: Tesla P40
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 10.2, V10.2.89
GCC: gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
PyTorch: 1.9.0+cu102
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.1.2 (Git Hash 98be7e8afa711dc9b66c8ff3504129cb82013cdb)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.2
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70
  - CuDNN 7.6.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=10.2, CUDNN_VERSION=7.6.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.9.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.10.0+cu102
OpenCV: 4.6.0
MMCV: 1.4.3
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 10.2
MMDetection: 2.20.0+

不确定是不是我得环境导致的

**Comment by zhaoguoqing12** [comment]
最郁闷的是有时候还不报错，直接中断了。我没法搞清楚到底是因为什么。

**Comment by ymy-k** [comment]
我训练的时候没有这些问题，估计还是环境导致的

**Comment by ymy-k** [comment]
我训练的时候倒是没有碰到这些问题，应该主要还是数据和环境的问题

**Comment by zhaoguoqing12** [comment]
我重新换个环境配置试一下

**Comment by ymy-k** [comment]
readme里面的运行命令有试过不

**Comment by zhaoguoqing12** [comment]
用过 但是不能完全使用 我需要指定gpu

**Comment by ymy-k** [comment]
指定gpu没用？有没有一种可能是CUDA_VISIBLE_DEVICES=1,2(不确定您是不是只在这个Issue下打错)

**Comment by zhaoguoqing12** [comment]
打错了，使用CUDA_VISIBLE_DEVICES=1,2是有用的，但是train.py中的命令行参数貌似没效果。

**Comment by ymy-k** [comment]
哪个参数，你咋用的

**Comment by zhaoguoqing12** [comment]
感觉是我不配训练，内存扛不住
220G内存不够用
![image](https://user-images.githubusercontent.com/47818312/184614595-f05eaae4-bafb-4303-b696-8eb794a805f8.png)

**Comment by zhaoguoqing12** [comment]
![image](https://user-images.githubusercontent.com/47818312/184614702-d42caf19-39ba-441a-8e15-42370910c468.png)
观察训练一段时间后，内存直接满了。然后被系统kill了
