### ISSUE TITLE
复现结果和表格相差一个多点？

### ISSUE THREAD

**Issue by 1700127** [ViTAE-Transformer/ViTAE-Transformer-Scene-Text-Detection#3]
<img width="849" alt="image" src="https://user-images.githubusercontent.com/43924063/184101346-b635d039-f579-47a6-a842-5f8acfdbe1c4.png">
作者你好，我用python -m torch.distributed.launch --nproc_per_node=4 --master_port=29500 tools/train.py \
configs/i3cl_vitae_fpn/i3cl_vitae_fpn_ms_train.py --launcher pytorch --work-dir ./out_dir/${your_dir}复现了下vitae的结果，训练数据用的是art_light，art_sig，art_noise，lsvt以及mlt19，和项目中一致，配置都是完全一样，但是结果相差一个多点，请问会是什么原因呢

**Comment by ymy-k** [comment]
数据是art, art_light，art_sig，art_noise，lsvt以及mlt19，那用backbone预训练的参数初始化了吗，推理的置信度也一样吗

**Comment by ymy-k** [comment]
数据是art, art_light，art_sig，art_noise，lsvt以及mlt19，那用ViTAE预训练的参数初始化backbone部分了吗，推理的置信度也一样吗

**Comment by 1700127** [comment]
> 数据是art, art_light，art_sig，art_noise，lsvt以及mlt19，那用ViTAE预训练的参数初始化backbone部分了吗，推理的置信度也一样吗

是这些数据，也是用你提供的模型pretrained_model/ViTAE/model_best.pth.tar初始化backbone部分参数，推理置信度用的默认值0.45，训练了两次，结果都是差一个多点

**Comment by ymy-k** [comment]
那你那边用提供的训好的整个模型直接测试F值是78.9吗，看有没有环境影响

**Comment by 1700127** [comment]
是的，用你提供的训练好的模型pretrained_model/I3CL/vitae_epoch_12.pth直接测试结果F值是78.9

**Comment by 1700127** [comment]
是的，我都按照这个步骤来的
<img width="865" alt="image" src="https://user-images.githubusercontent.com/43924063/184132804-4842b8ea-5f7a-4c61-99c6-da92d46a9a52.png">

**Comment by 1700127** [comment]
另外，想问下我训练自己的数据时能否用你训练好的vitae_epoch_12.pth模型初始化backbone参数，而不是用原始的model_best.pth.tar（imagenet上训练得到？）模型初始化，理论上用vitae_epoch_12.pth初始化参数效果应该会更好些？
![image](https://user-images.githubusercontent.com/43924063/184133645-feaf0a62-35ec-4321-9341-8079b5ea56e5.png)

**Comment by ymy-k** [comment]
Hi～校对后更新了下配置文件，可以再试一下，可能是数据增强那块这几行与78.9用的配置有出入[config](https://github.com/ViTAE-Transformer/ViTAE-Transformer-Scene-Text-Detection/blob/89828a94dca89ff1fac5c7cbbaa9d5c556de9b4b/configs/i3cl_vitae_fpn/coco_instance.py#L14-L17)，AutoAugment只在这个复现论文结果的仓库里使用了

**Comment by ymy-k** [comment]
> 另外，想问下我训练自己的数据时能否用你训练好的vitae_epoch_12.pth模型初始化backbone参数，而不是用原始的model_best.pth.tar（imagenet上训练得到？）模型初始化，理论上用vitae_epoch_12.pth初始化参数效果应该会更好些？ ![image](https://user-images.githubusercontent.com/43924063/184133645-feaf0a62-35ec-4321-9341-8079b5ea56e5.png)

因为不太清楚您数据的情况，建议先拿一些数据实验一下

**Comment by 1700127** [comment]
> Hi～校对后更新了下配置文件，可以再试一下，可能是数据增强那块这几行与78.9用的配置有出入[config](https://github.com/ViTAE-Transformer/ViTAE-Transformer-Scene-Text-Detection/blob/89828a94dca89ff1fac5c7cbbaa9d5c556de9b4b/configs/i3cl_vitae_fpn/coco_instance.py#L14-L17)，AutoAugment只在这个复现论文结果的仓库里使用了

好的，我更新下配置文件然后再试试

**Comment by 1700127** [comment]
> 


> Hi～校对后更新了下配置文件，可以再试一下，可能是数据增强那块这几行与78.9用的配置有出入[config](https://github.com/ViTAE-Transformer/ViTAE-Transformer-Scene-Text-Detection/blob/89828a94dca89ff1fac5c7cbbaa9d5c556de9b4b/configs/i3cl_vitae_fpn/coco_instance.py#L14-L17)，AutoAugment只在这个复现论文结果的仓库里使用了

更新了配置文件重新复现了下，结果F值还是相差一个多点，确定78.9的是单尺度测试的结果吗？
![image](https://user-images.githubusercontent.com/43924063/184493022-15a2f358-047e-46c1-b52d-53d49950662c.png)

**Comment by ymy-k** [comment]
确定

**Comment by 1700127** [comment]
> 确定

hi，你测试时是用的这个尺度吗
<img width="441" alt="image" src="https://user-images.githubusercontent.com/43924063/184604006-df912abc-555b-4415-9576-58b798ed66b7.png">
