### ISSUE TITLE
作者您好，相似区域检测不出来文字和适用于中文文本检测的论文

### ISSUE THREAD

**Issue by aibohang** [ViTAE-Transformer/ViTAE-Transformer-Scene-Text-Detection#6]
作者您好，我在阅读您的论文和代码中收获了很多，这篇论文带给我很大帮助，但我在测试预测图像时候遇到一个问题：我将视频转成图像，用您的算法进行推理检测图中的文字，相邻的某几帧图像一开始在该区域可以检测到文字，过了几帧后突然检测不出来文字（这个文字区域和之前检测到的文字区域内容大小都一模一样），但后面又能检测出来的情况，请问这个是因为用的训练数据集的原因，还是其他原因呐？麻烦您能在空闲时候回复下，十分感谢！  还有一个问题：请问您有检测中英文文本的其他论文推荐吗？

**Comment by ymy-k** [comment]
请问有您提及问题的检测结果示例吗，不太清楚具体情况是怎样的
